server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: casb-admin
    version: 1.0.0
    description: Spring Boot Admin Service with MyBatis integration
    # 注意：作者信息建议通过其他方式记录，或根据实际情况调整格式
#  数据库配置
  datasource:
   url: jdbc:mysql://localhost:3306/jxcxt?useSSL=false&serverTimezone=UTC
   username: root
   password: 123456
   driver-class-name: com.mysql.cj.jdbc.Driver
#   分页插件配置
pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: "com.casb.casbadmin;"
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml,classpath*:mapper/**/*.xml
  # MyBatis全局配置
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true